# 888    d8P  8888888888 8888888b.  888b     d888 8888888 888b    888        d8888 888
# 888   d8P   888        888   Y88b 8888b   d8888   888   8888b   888       d88888 888
# 888  d8P    888        888    888 88888b.d88888   888   88888b  888      d88P888 888
# 888d88K     8888888    888   d88P 888Y88888P888   888   888Y88b 888     d88P 888 888
# 8888888b    888        8888888P"  888 Y888P 888   888   888 Y88b888    d88P  888 888
# 888  Y88b   888        888 T88b   888  Y8P  888   888   888  Y88888   d88P   888 888
# 888   Y88b  888        888  T88b  888   "   888   888   888   Y8888  d8888888888 888
# 888    Y88b 8888888888 888   T88b 888       888 8888888 888    Y888 d88P     888 88888888
#

Database:
  type: "sqlite" # sqlite ou mysql
  sqlite:
    fileName: "database.db"
  mysql:
    address: "localhost:3306"
    username: "root"
    password: ""
    database: "kerminal"

########################################
#      Bloquear nicks improprios       #
########################################
BlockedPlayerNames:
  - "CONSOLE"
  - "CONSOLE_COMMAND"
  - "CONSOLE_PLAYER"
  - "MCSTORM_IO"

########################################
#      Placa de reparar       #
########################################
SignRepair:
  Enabled: true
  SignModel:
    - "&a[Reparar]"
    - "&7Clique para"
    - "&7reparar"

########################################
#      Bloquear craft de itens         #
########################################
Crafts:
  # Escreva abaixo os materiais dos itens bloqueados
  Blacklist:
    - "EXAMPLE"

########################################
#           Knockback da TNT           #
########################################
ExplosionRepulse:
  Enabled: false
  RemoveDamage: true
  Repulsion: 10.0

########################################
#                 Motd                 #
########################################
Motd:
  MaxPlayers: 10
  Normal:
    - "&aFirst motd"
    - "&bSecond motd"
    - "&cThird motd"
  Maintenance:
    - "&aThis server in Maintenance"
    - "&bThis server in Maintenance"
    - "&cThis server in Maintenance"

########################################
#                 TAB                  #
########################################
TAB:
  Header:
    - ""
    - ""
    - "ᦽ"
    - ""
    - ""
    - ""
    - ""
  Footer:
    - "  &6Twitter:&f twitter.com/minevil"
    - "  &6Discord:&f discord.io/minevil"
    - ""
    - "  &dCompre VIP acessando &floja.minevil.com.br"
    - ""
    - ""

########################################
#             Teleportes               #
########################################
Teleport:
  # Defina o tempo de teleportar (EM SEGUNDOS)
  Delay: 3
  # Defina o tempo que o jogador não recebá danos após teleportar
  InvencibleDelay: 3
  Effect: ENDER_SIGNAL
  Sound: ENTITY_ENDERMAN_TELEPORT


########################################
#             Regeneração              #
########################################
Regeneration:
  # Ative ou desative o sistema
  Enabled: false
  # Defina o tempo da regeneração da vida (EM TICKS)
  Delay: 20

########################################
#         Comandos Bloqueados          #
########################################
BlockedCommands:
  - "plugins"
  - "pl"

########################################
#       Mensagem de boas vindas        #
########################################
Welcome:
  SendTitle:
    Enabled: true
    Title: "&eKerminal"
    Subtitle: "&7Bem-vindo ao servidor!"
  Message:
    Enabled: true
    Text:
      - ""
      - ""
      - "&9Este servidor utiliza Kerminal! Bem-vindo!"
      - ""
      - ""

########################################
#        Recursos do Kerminal          #
########################################
Features:
  # Permite trocar as mensagens de Entrada, Saida e Morte
  CustomMessages:
    Enabled: true
    # Para não exibir nenhuma mensagem, deixe vazio.
    # Placeholders: %player% (Nome do jogador)
    PlayerJoin: ""
    # Para não exibir nenhuma mensagem, deixe vazio.
    # Placeholders: %player% (Nome do jogador)
    PlayerQuit: ""
    # Configuração da mensagem de morte
    PlayerDeath:
      # Modos:
      # ALL - Exibe a mensagem default para todos online
      # PRIVATE - Exibe as mensagens privadas apenas para assassino e vitima
      Mode: ALL
      # Para não exibir nenhuma mensagem, deixe vazio.
      DefaultMessage: ""
      PrivateAnnounces:
        Killer: "&aVocê acabou de matar %player%."
        Victim: "&aVocê foi morto por %player%."
  # Envia mensagens aos jogadores de tempo em tempo
  AutoMessage:
    Enabled: true
    # Intervalo de tempo entre as mensagens
    # O valor está em segundos
    Delay: 240
    # Som que será enviado para todos a cada mensagem
    # Para não realizar nenhum som, defina como: "false"
    Sound: CAT_MEOW
    # Lista de mensagens automáticas em ordem
    Messages:
      - "&a【Anúncio】 &fObrigado por usar o Kerminal :3"
      - "&a【Anúncio】 &fO que acha de mandar o Kerminal para seus amigos?"
      - "&a【Anúncio】 &fSe precisar falar com os desenvolvedores, entre na BeezCommunity."
      - "&a【Anúncio】 &fQuer adicionar algo no Kerminal? Envia sua sugestão para nós ;)"
  # Habilitar ou desabilitar Drop de Cabeça
  Heads:
    Enabled: true
    # Chance de dropar no chão
    Chance: 100
    # Formato do nome da cabeça
    # Caso não queira um nome, deixe vazio
    Name: "&aCabeça do jogador %player%"
    # Descrição da cabeça
    # Caso não queira uma descrição, coloque -> Lore: {}
    Lore:
      - "&7É uma cabeça especial"

  # Algumas opções para customizar o servidor
  Options:
    # Bloqueia a queda das folhas das arvores
    Block-Decay-Leaves: true
    # Bloqueia o jogador de cair no void (Teleporta pro spawn)
    Block-Void-Damage: true
    # Bloqueia de ocorrer chuvas
    Block-Weather: true
    # Bloqueia de derreter o gelo
    Block-Smelt-Snow: true
    # Bloqueia de criar portais
    Block-Create-Portal: true
    # Bloqueia os jogadores de ficarem com fome
    # Na lista abaixo é definido os mundos que ficarão sem fome
    Block-Food-Down: true
    FoodWorlds:
      - "world"
    # Bloqueia itens de explodirem
    Block-Explode-Item: true
    # Bloqueia plantações de quebrarem pulando
    Block-Plantation-Destroy: true
    # Bloqueia de congelar a água
    Block-Freeze-Water: true
    # Bloqueia as entidades de pegarem fogo
    Block-Entity-Burn: true
    # Bloqueia as entidades de roubarem itens
    Block-Entity-Steal-Item: true
    # Bloqueia o fogo de se espalhar pelo mapa
    Block-Fire-Spred: true
    # Bloqueia de subir em veículos
    Block-Vehicle-Enter: true
    # Bloqueia entidades de nascerem naturalmente
    Block-Naturally-Spawn: false

########################################
#       Opções de bloquear mundos      #
########################################
BlockedWorlds:
  Fly:
    - "exampleWorld"
  BackCommand:
    - "exampleWorld"
  HomeCommand:
    - "exampleWorld"

########################################
#      Opções dos Mundos em Ticks      #
########################################
Worlds:
  # Defina o nome do mundo
  world:
    # A quantidade da aceleração dos ticks do mundo
    # Isso afetará o crescimento de plantações, grama, etc...
    Tick: 60